name: webdevjohn-basetheme
recipe: wordpress
config:
  php: '8.1'
  webroot: web
services:
  appserver:
    build_as_root:
      - apt-get update -qq && apt-get install -y -qq mysql-client
    overrides:
      environment:
        WP_ENV: 'development'
        WP_HOME: 'http://webdevjohn-basetheme.lndo.site'
        WP_SITEURL: '${WP_HOME}/wp'